# Generated by Django 4.2.7 on 2023-11-24 06:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ListBookAPI', '0001_initial'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='book',
            name='ListBookAPI_price_27506a_idx',
        ),
    ]
